# Generated by Django 3.1.2 on 2020-11-18 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_planner', '0002_auto_20201117_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rangequery',
            old_name='exercise',
            new_name='exercise_query',
        ),
    ]
