# Generated by Django 3.1.2 on 2020-11-18 15:09

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('training_planner', '0003_auto_20201118_1354'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='range',
            name='min_max',
        ),
        migrations.AddConstraint(
            model_name='range',
            constraint=models.CheckConstraint(check=models.Q(minimum__lte=django.db.models.expressions.F('maximum')), name='Range_min_max'),
        ),
        migrations.AddConstraint(
            model_name='valuequery',
            constraint=models.CheckConstraint(check=models.Q(minimum__lte=django.db.models.expressions.F('maximum')), name='ValueQuery_min_max'),
        ),
        migrations.AddConstraint(
            model_name='valuequery',
            constraint=models.UniqueConstraint(fields=('unit', 'exercise_query'), name='unique_unit_exercise_query'),
        ),
    ]
