# Generated by Django 3.1.2 on 2020-11-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_planner', '0004_auto_20201118_1509'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='range',
            name='unique_unit_exercise',
        ),
        migrations.RemoveConstraint(
            model_name='valuequery',
            name='unique_unit_exercise_query',
        ),
        migrations.AddConstraint(
            model_name='range',
            constraint=models.UniqueConstraint(fields=('unit', 'exercise'), name='Range: unique_unit_exercise'),
        ),
        migrations.AddConstraint(
            model_name='rangequery',
            constraint=models.UniqueConstraint(fields=('unit', 'exercise_query'), name='RangeQuery: unique_unit_exercise'),
        ),
        migrations.AddConstraint(
            model_name='value',
            constraint=models.UniqueConstraint(fields=('unit', 'exercise'), name='Value: unique_unit_exercise'),
        ),
        migrations.AddConstraint(
            model_name='valuequery',
            constraint=models.UniqueConstraint(fields=('unit', 'exercise_query'), name='ValueQuery: unique_unit_exercise_query'),
        ),
    ]
