# Generated by Django 3.1.2 on 2020-11-25 12:24

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('training_planner', '0005_auto_20201118_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuequery',
            name='function',
            field=models.TextField(choices=[('SUM', 'Sum'), ('MEAN', 'Mean')], default='Sum'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='range',
            name='minimum',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='valuequery',
            name='minimum',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TrainingsValueQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum', models.PositiveIntegerField(blank=True, null=True)),
                ('maximum', models.PositiveIntegerField(blank=True, null=True)),
                ('trainings_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_planner.trainingsquery')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_planner.valueunit')),
            ],
        ),
        migrations.AddField(
            model_name='trainingsquery',
            name='value_query',
            field=models.ManyToManyField(blank=True, related_name='_trainingsquery_value_query_+', through='training_planner.TrainingsValueQuery', to='training_planner.ValueUnit'),
        ),
        migrations.AddConstraint(
            model_name='trainingsvaluequery',
            constraint=models.CheckConstraint(check=models.Q(minimum__lte=django.db.models.expressions.F('maximum')), name='TrainingsValueQuery_min_max'),
        ),
        # migrations.AddConstraint(
        #     model_name='trainingsvaluequery',
        #     constraint=models.UniqueConstraint(fields=('unit', 'exercise_query'), name='TrainingsValueQuery: unique_unit_exercise_query'),
        # ),
    ]
