# Generated by Django 3.1.2 on 2020-11-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_planner', '0006_auto_20201125_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valuequery',
            name='function',
        ),
        migrations.AddField(
            model_name='trainingsvaluequery',
            name='function',
            field=models.TextField(choices=[('SUM', 'Sum'), ('MEAN', 'Mean')], default='Sum'),
            preserve_default=False,
        ),
    ]
