# Generated by Django 3.1.2 on 2020-11-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_planner', '0007_auto_20201125_1226'),
    ]

    operations = [
        # migrations.RemoveConstraint(
        #     model_name='trainingsvaluequery',
        #     name='TrainingsValueQuery: unique_unit_exercise_query',
        # ),
        migrations.AddConstraint(
            model_name='trainingsvaluequery',
            constraint=models.UniqueConstraint(fields=('unit', 'trainings_query'), name='TrainingsValueQuery: unique_unit_exercise_query'),
        ),
    ]
