# Generated by Django 3.1.2 on 2020-11-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_planner', '0008_auto_20201125_1228'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='trainingsvaluequery',
            name='TrainingsValueQuery: unique_unit_exercise_query',
        ),
        migrations.AddConstraint(
            model_name='trainingsvaluequery',
            constraint=models.UniqueConstraint(fields=('unit', 'function', 'trainings_query'), name='TrainingsValueQuery: unique_unit_exercise_query'),
        ),
    ]
