# Generated by Django 3.1.2 on 2020-11-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_planner', '0009_auto_20201125_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisequery',
            name='description',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='exercisequery',
            name='name',
            field=models.CharField(default='UNNAMED', max_length=200),
            preserve_default=False,
        ),
    ]
