# Generated by Django 3.1.2 on 2020-11-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_planner', '0010_auto_20201125_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingsquery',
            name='value_query',
        ),
        migrations.AddField(
            model_name='trainingsquery',
            name='value_queries',
            field=models.ManyToManyField(blank=True, related_name='_trainingsquery_value_queries_+', through='training_planner.TrainingsValueQuery', to='training_planner.ValueUnit'),
        ),
    ]
