# Generated by Django 3.1.2 on 2020-11-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_planner', '0011_auto_20201125_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rangequery',
            name='value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
